version: "3"

services:
  nextjs-app:
    image: ghcr.io/tunglam99/nextjs-app:dev-latest
    ports:
      - "4000:4000" # Different port for dev
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    platform: linux/x86_64
    volumes:
      - ./public:/usr/share/nginx/html/public # Make sure the public folder is correctly mounted

  nginx:
    image: nginx:latest
    depends_on:
      - nextjs-app
    ports:
      - "80:80" # Different port for dev
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Separate config for dev
      - ./public:/usr/share/nginx/html/public # Make sure the public folder is accessible
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    platform: linux/x86_64
